name: automap
description: A lightweight object mapper for Dart, with support for automatic JSON-based mapping and manual mapping expressions.
version: 0.1.0
repository: https://github.com/leynier/automap-dart
issue_tracker: https://github.com/leynier/automap-dart/issues

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
