name: automap
description: An auto mapper for Dart. It allows mapping objects of different classes automatically and manually using JSON serialization.
version: 0.0.3
repository: https://github.com/leynier/automap-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.5.3
